"""
Markdown reporter for threat intelligence verdicts.
"""

import os
from typing import List
from ..models import Verdict, EvidenceItem


class MarkdownReporter:
    """Generates Markdown reports from verdicts."""

    def generate(self, verdict: Verdict) -> str:
        """
        Generate Markdown report from verdict.

        Args:
            verdict: Analysis verdict

        Returns:
            Markdown string representation
        """
        lines = []

        # Title
        lines.append(f"# Threat Intelligence Analysis Report")
        lines.append("")

        # Object Summary
        lines.append("## Object Summary")
        lines.append("")
        lines.append(f"- **Type**: {verdict.object_type.upper()}")
        lines.append(f"- **Value**: `{verdict.object_value}`")
        lines.append("")

        # Analysis Results
        lines.append("## Analysis Results")
        lines.append("")
        lines.append(f"- **Final Score**: {verdict.final_score}/100")
        lines.append(f"- **Reputation Score**: {verdict.reputation_score}")
        lines.append(f"- **Contextual Score**: {verdict.contextual_score}")
        lines.append(f"- **Verdict Level**: {self._format_level(verdict.level)}")
        lines.append(f"- **Confidence**: {verdict.confidence:.2%}")
        lines.append(
            f"- **Recommended Action**: {self._format_decision(verdict.decision)}"
        )
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append(verdict.summary)
        lines.append("")

        # Semantic Tags
        if verdict.tags:
            lines.append("## Semantic Tags")
            lines.append("")
            for tag in verdict.tags:
                lines.append(f"- `{tag}`")
            lines.append("")

        # Evidence
        if verdict.evidence:
            lines.append("## Evidence")
            lines.append("")

            # Group evidence by source
            sources = {}
            for evidence in verdict.evidence:
                if evidence.source not in sources:
                    sources[evidence.source] = []
                sources[evidence.source].append(evidence)

            for source, evidences in sources.items():
                lines.append(f"### {source.upper()}")
                lines.append("")

                for evidence in evidences:
                    lines.append(f"**{evidence.title}**")
                    lines.append(f"- Severity: {evidence.severity}")
                    lines.append(f"- Score Impact: {evidence.score_delta:+d}")
                    lines.append(f"- Confidence: {evidence.confidence:.2%}")
                    lines.append(f"- Details: {evidence.detail}")
                    lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append(
            "*Report generated by Threat Intelligence Reasoning Engine v0.1.0*"
        )

        return "\n".join(lines)

    def _format_level(self, level: str) -> str:
        """Format verdict level with color indicators."""
        colors = {
            "Low": "🟢 Low",
            "Medium": "🟡 Medium",
            "High": "🟠 High",
            "Critical": "🔴 Critical",
            "Inconclusive": "⚪ Inconclusive",
        }
        return colors.get(level, level)

    def _format_decision(self, decision: str) -> str:
        """Format decision for readability."""
        decision_map = {
            "allow_with_monitoring": "Allow with Monitoring",
            "investigate": "Investigate",
            "alert_and_review": "Alert and Review",
            "contain_or_block": "Contain or Block",
            "collect_more_context": "Collect More Context",
        }
        return decision_map.get(decision, decision.replace("_", " ").title())
